Fixes to EL8 TPC

diff --git a/bootstrap-osg-test b/bootstrap-osg-test
--- a/bootstrap-osg-test
+++ b/bootstrap-osg-test
@@ -41,6 +41,7 @@ case $release in
     *8.* )
 	rpm_name='epel-release-latest-8.noarch.rpm'
         osg_name="osg-$version-el8-release-latest.rpm"
+	;;
     * )
         echo 'Could not determine OS release'
         exit 1
@@ -86,13 +87,24 @@ echo -n 'Updating osg-release... '
 yum -y --quiet update osg-release
 on_error_die 'Could not update osg-release'
 
-echo -n "Install yum-plugin-priorities... "
-yum -y --quiet install yum-plugin-priorities
-on_error_die "Could not install yum-plugin-priorities"
-echo -n 'Verify yum-plugin-priorities... '
-rpm --verify yum-plugin-priorities
-on_error_die "Could not verify yum-plugin-priorities"
-
+case $release in
+    *[6|7].* )
+	echo -n "Install yum-plugin-priorities... (For EL6, EL7 only)"
+	yum -y --quiet install yum-plugin-priorities
+        on_error_die "Could not install yum-plugin-priorities"
+        echo -n 'Verify yum-plugin-priorities... '
+        rpm --verify yum-plugin-priorities
+        on_error_die "Could not verify yum-plugin-priorities"
+        ;;
+    *8.* )
+        echo -n "Not installing plugin priorities in EL8"
+        ;;
+    * )
+        echo 'Could not determine OS release'
+        exit 1
+        ;;
+esac
+    
 cd /tmp
 for repo in osg-test osg-ca-generator; do
     git clone --depth 1 $UPSTREAM/$repo
